# Generated by Django 6.0 on 2025-12-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=20),
        ),
    ]
